pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('hello-world') {
                    bat 'mvn clean package'
                }
            }
        }

    }
}