pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
                echo 'Cloning from GitHub'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean package'
            }
        }

    }
}